baseurl: ""
url: ""
tickets_url: https://www.boroondara.vic.gov.au/events/camberwell-showtime-snowed-inn
members_area_url: //private.camberwellshowtime.com/

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

jekyll-minifier:
  preserve_line_breaks: true
  compress_css: false
  exclude: '*.css'

timezone: Australia/Melbourne
