backend:
  name: git-gateway

media_folder: uploads # Folder where user uploaded files should go

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "snippets" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Snippet" # Used in the UI, ie.: "New Post"
    folder: "_includes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "index.html"
  - name: "layout"
    label: "Layout"
    files:
      - name: "layout"
        label: "Layout"
        file: "_layouts/default.html"
  - name: "data"
    label: "Data"
    editor:
      preview: false
    files:
      - name: "general" # Used in routes, ie.: /admin/collections/:slug/edit
        label: "General" # Used in the UI, ie.: "New Post"
        file: "_data/general.yml"
        create: false
        fields: # The fields each document in this collection have
          - {label: "Tickets URL", name: "tickets_url", widget: "string", required: false}
          - {label: "Member's area URL", name: "members_area_url", widget: "string", required: false}
      - name: "contacts"
        label: "Contacts"
        file: "_data/contacts.yml"
        fields:
          - label: "Contact"
            name: "contacts"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "text"}
              - {label: "Email", name: "email", widget: "text", required: false}
              - {label: "Href", name: "href", widget: "text", required: false}
      - name: "performances"
        label: "Performances"
        file: "_data/performances.yml"
        fields:
          - label: "Performance"
            name: "performances"
            widget: "list"
            fields:
              - {label: "Date (datetime)", name: "date", widget: "datetime"}
              - {label: "Description", name: "description", widget: "text"}
      - name: "cast"
        label: "Cast dates"
        file: "_data/cast.yml"
        fields:
          - label: "Cast date"
            name: "cast"
            widget: "list"
            fields:
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Date (text)", name: "date", widget: "text"}
